name: Build Debug APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 1) Accept licenses (jangan gagal walau ada 'Broken pipe')
      - name: Accept SDK licenses (no-fail)
        shell: bash
        run: |
          yes | sdkmanager --licenses >/dev/null 2>&1 || true

      # 2) Install paket SDK (dengan fallback versi build-tools)
      - name: Install SDK packages
        shell: bash
        run: |
          set -e
          sdkmanager "platform-tools" "platforms;android-34"
          # coba 34.0.0, kalau tidak ada coba 35.0.0
          sdkmanager "build-tools;34.0.0" || sdkmanager "build-tools;35.0.0"

      # (Opsional) Validasi wrapper; hapus step ini bila nanti error karena jar tidak ada
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      # Build aman via Gradle Build Action (tidak ada argumen nempel URL)
      - name: Build with Gradle (debug)
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ":app:assembleDebug"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ParkirKece-APK
          path: app/build/outputs/apk/debug/*.apk
